### ISSUE TITLE
Document: Implement JSON serialization

### ISSUE THREAD

**Issue by franzliedke** [tobscure/json-api#10]
Can we have the `Document` class implement the [`JsonSerializable` interface](http://php.net/manual/en/class.jsonserializable.php)?
I'd love to have that for easier JSON response creation in Flarum.

That would also require changing the version requirement to PHP 5.4.

**Comment by tobscure** [comment]
Yep, can you send a PR?

**Comment by franzliedke** [comment]
Will do.
