### ISSUE TITLE
Use a getter to retrieve id

### ISSUE THREAD

**Issue by rgazelot** [tobscure/json-api#109]
According to the JSON-API specification, a resource's identifier named `id` must be unique in the given resource domain. http://jsonapi.org/format/#document-resource-object-identification

In most of our applications, our classes which represent these resources have this property as a private to avoid the rest of the application to change this one and corrupt the database for example.

What about to change the following lines to use a getter instead of trying to directly access to the `id` property and have to extends this method in our custom serializer every time ?

```php
# Tobscure\JsonApi\AbstractSerializer.php

/**
     * {@inheritdoc}
     */
    public function getId($model)
    {
        return $model->getId();
    }
```

**Comment by tobscure** [comment]
You can create your own custom AbstractSerializer as a base for your other serializers to reduce duplication:

```php
use Tobscure\JsonApi\AbstractSerializer as BaseSerializer;
class AbstractSerializer extends BaseSerializer {
    public function getId($model)
    {
        return $model->getId();
    }
}
class UserSerializer extends AbstractSerializer {
}
class PostSerializer extends AbstractSerializer {
}
```

In terms of using `->id` vs `->getId()` by default, I think it makes sense to preference simple objects (ie the former) as in Laravel's Eloquent ORM. If anything, we would eliminate this preference altogether and make `AbstractSerializer::getId` an abstract method requiring implementation by the user, but I don't see any reason to do this.
