### ISSUE TITLE
Add a JSON-API validator?

### ISSUE THREAD

**Issue by rgazelot** [tobscure/json-api#121]
What do you think about if your library could be able to validate a given json depending on the JSON-API specification part about [creating and updating resources](http://jsonapi.org/format/#crud-creating)?

I'm using your library to serialize my resources for the output. It could be interesting to use it to validate the incoming data too.

**Comment by tobscure** [comment]
I think that's a great idea for another library, but it's beyond the scope of what I want this library to do. This library is about building documents :)

**Comment by tobscure** [comment]
@rgazelot see https://github.com/tobscure/json-api/issues/126#issuecomment-290357767
