### ISSUE TITLE
Add relationships without included part

### ISSUE THREAD

**Issue by rgazelot** [tobscure/json-api#128]
Hi @tobscure 

Is there a way to expose the relationships of an object without the `included` part added automatically? Thanks for your help.

**Comment by tobscure** [comment]
Instead of passing a model, you can pass an ID (string) when creating a Resource, or an array of IDs when creating a Collection. Here's an example:

```php
// PostSerializer
public function comments($post) {
    $commentIds = array_map(function ($comment) {
        return $comment->id;
    }, $post->comments);

    $element = new Collection($commentIds, new CommentSerializer);

    return new Relationship($element);
}
```

**Comment by rgazelot** [comment]
@tobscure Thanks for your help. Do you want to include this point into your README, because it's very useful for frontend framework to have just relationships without included data and it is not in the documentation. I can open a PR if you want.

**Comment by tobscure** [comment]
@rgazelot that'd be great thanks!
