### ISSUE TITLE
Collection shouldn't have to need a serializer in case of Resource collection

### ISSUE THREAD

**Issue by rgazelot** [tobscure/json-api#132]
The [Collection::__construct()](https://github.com/tobscure/json-api/blob/master/src/Collection.php#L27) need a `SerializerInterface` as second argument, but if the `$data` argument is an array of `Resource` object, this interface is never used. It should be nullable in order to fill the `Collection` with an array of `Resource` objects.

**Comment by tobscure** [comment]
This is fixed in https://github.com/tobscure/json-api/pull/119

**Comment by rgazelot** [comment]
@tobscure Great! I would have to have a better reading about the PRs.
