### ISSUE TITLE
Allow prepending handlers to ErrorHandler

### ISSUE THREAD

**Issue by CDK2020** [tobscure/json-api#133]
Currently, if one uses the `FallBackExceptionHandler`, (Flarum) it prevents people from adding custom handlers after. 

If you set `$handlers` to public, or add some way to prepend handlers in `ErrorHandler`, this would solve that problem.

**Comment by tobscure** [comment]
Error handling is being removed in the [next version](https://github.com/tobscure/json-api/pull/119), so this won't be relevant :)
