### ISSUE TITLE
Response when resource not found

### ISSUE THREAD

**Issue by piotrgolasz** [tobscure/json-api#136]
According to http://jsonapi.org/format/#fetching-resources, when a resource is not found, the API should return
```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1/author"
  },
  "data": null
}
```

Can you provide an example how to achieve this, this example is not described in README.

**Comment by franzliedke** [comment]
Note that this is not for *every* resource that is not found, just for to-one relationships (like in this case, the one author that belongs to article no. 1).

For others, we have this rule:

> 404 Not Found
> A server MUST respond with 404 Not Found when processing a request to fetch a single resource that does not exist, except when the request warrants a 200 OK response with null as the primary data (as described above).

**Comment by piotrgolasz** [comment]
Right, thank you.
