### ISSUE TITLE
Resource word is reserved in PHP7

### ISSUE THREAD

**Issue by a-komarev** [tobscure/json-api#140]
This is just a notice that PHP7 has `Resource` class name as soft-reserved word. There could be possibility to face the situation when in future versions of PHP this library will be broken.

https://secure.php.net/manual/en/reserved.other-reserved-words.php

*Note: All the reserved words are case-insensitive. If `object` is reserved that means `Object` is reserved too.*

**Comment by f3ath** [comment]
Good point. `ResourceObject` sounds like a legit option to me.

**Comment by tobscure** [comment]
If you look at [the source](https://github.com/tobscure/json-api/tree/resource-interface/src) for the upcoming version, we no longer have a `Resource` class (only `ResourceInterface`, `ResourceIdentifier`, `ResourceObject`, and `AbstractResource`). So no issue?

**Comment by a-komarev** [comment]
This issue will be solved after PR #119 merge. Closing it.
