### ISSUE TITLE
Fatal error:  Call to undefined function Tobscure\\JsonApi\\array_get()

### ISSUE THREAD

**Issue by xbill82** [tobscure/json-api#15]
Hi,
First of all, thank you for the great job! :+1: 

I encountered the following error when using `Relationship`s

     PHP Fatal error:  Call to undefined function Tobscure\\JsonApi\\array_get() in /opt/ami/Ami/web/rest/vendor/tobscure/json-api/src/SerializerAbstract.php on line 108

So I tried to prefix the calls to `array_get` with `\` but the error persists. After googling a bit, I found that such a function isn't natively supported in PHP (I use >5.4), it's a Laravel helper function.
Maybe Laravel should be declared as a dependency?

If this sounds too overkill to you, I tried adding the following at the end of `SerializerAbstract` (right after the class)

    function array_get(array $array, $id, $fallback = '')
    {
        return isset($array[$id]) ? $array[$id] : $fallback;
    }

Which works.

Now, put in this way, right into the `SerializerAbstract.php` file, it's quite dirty. So, if you are ok with this solution (rather than Laravel as a dependency) I can put it into a `Utils.php` file and submit a pull request.

**Comment by EvgenyKovalev** [comment]
Laravel `array_get` is more complex and supports *dot path notation*. So if this package relies on this functionality it might cause an error. Sadly there is a lack of test coverage.

**Comment by tobscure** [comment]
It doesn't need dot path notation support. But including array_get is probably overkill, we should just clean up that if condition and use `isset($relationships['include'][$name]) ? $relationships['include'][$name] : []` directly.

I do intend to properly clean up + test + semver this package someday... hopefully I'll have time in a month or two 🌞

**Comment by xbill82** [comment]
Hi @EvgenyKovalev, no reason to be sad about the tests :smile: Let's put them together :construction_worker: 
By the way, the calls don't seem to rely on the dot path notation, so I guess we can use the simple version of the function.

**Comment by EvgenyKovalev** [comment]
@xbill82 I prefer using json-api v1.0 but not pre-release RC3 and use https://github.com/neomerx/json-api which has good test coverage
