### ISSUE TITLE
Move Issues of the Todos?

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#18]
I could help out you with this. @tobscure is it something you would consider? Maybe we could also create a label for version `1.0`?

**Comment by tobscure** [comment]
Yep that'd be great - PRs/issues appreciated. This package is powering [Flarum](http://flarum.org) so I do fully intend to get it stable and tested in the next few months.

**Comment by vinkla** [comment]
Great! Then I'll move them and send you a new PR in 10 minutes or so.
