### ISSUE TITLE
Fix broken link to Eloquent Relationship builder example

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#26]
Eloquent adapter to make relationships easier when using Laravel.

**Comment by tobscure** [comment]
Decided that this is outside the scope of the package, but is very easy to do with the new relationships stuff in 0.2 branch. There's a link in the docs to an example – currently broken because I haven't pushed the project yet, so I'll leave this open until i can fix that.

**Comment by vinkla** [comment]
Yeah, maybe we should create a Laravel wrapper later on instead?
