### ISSUE TITLE
Include By Default?

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#33]
How do I include a relationship by default from a serializer class? Is it possible?

**Comment by tobscure** [comment]
Nope – you must specify all of your default includes when constructing the top-level serializer:

```php
$serializer = new FooSerializer(['bar', 'bar.something']);
```

Theoretically wouldn't be hard to add in, but I've found that most default includes depend on the endpoint anyway (e.g. you would include more stuff on an endpoint that returns a single resource vs. a collection of resources)

**Comment by vinkla** [comment]
Okay, thank you.
