### ISSUE TITLE
Add PHP CS Fixer?

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#35]
What adding a [PHP CS fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) configuration file? Sounds interesting?

**Comment by tobscure** [comment]
Is this different to https://github.com/tobscure/json-api/blob/master/phpcs.xml ?

**Comment by vinkla** [comment]
Yeah, the PHP CS Fixer file doesn't just check the code, it fixes it as well. I'd argue for adding a .php_cs file and then adding this repository to https://styleci.io/. StyleCI will then check syntax for all commits and pull requests automagically.

**Comment by vinkla** [comment]
I could send a PR for this and then guide you through StyleCI.

**Comment by tobscure** [comment]
That'd be great :) I need to get travis set up too. Will try and find some time over the weekend.

**Comment by vinkla** [comment]
Cool, I'll push a travis config update as well then. Do you plan to add this repository to Scrutinizer?

**Comment by tobscure** [comment]
Sure why not :)

**Comment by vinkla** [comment]
Great! Then I'll add that too :)
