### ISSUE TITLE
Empty Relation

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#57]
Currently (0.1.1) the package throws an error if the relation the client is trying to include a relation doesn't exist. What is expected behaviour? Should it throw an error?

```php
return new Relation($resource); // throws and error if $resource is null
```

Maybe this should just return empty instead?

**Comment by tobscure** [comment]
You should only create a Relationship object if there is relationship data – otherwise just return null. I don't think this is an issue in the 0.2 branch because the Builder automatically checks this for you.

**Comment by vinkla** [comment]
That's great. Thanks.
