### ISSUE TITLE
Add links & meta to collection items via Serializer?

### ISSUE THREAD

**Issue by bnchdrff** [tobscure/json-api#64]
Would it make sense to offer methods `getLinks` and `getMeta` that would act in a similar way to `getAttributes`?

**Comment by tobscure** [comment]
I think so, yes.

**Comment by bwaidelich** [comment]
:+1: this would be required in order to create self-discoverable APIs IMO

**Comment by tobscure** [comment]
@bwaidelich would you like to do a PR for the `meta` equivalent?

**Comment by bwaidelich** [comment]
@tobscure there you go: #81
