### ISSUE TITLE
Better Laravel Eloquent Support

### ISSUE THREAD

**Issue by vinkla** [tobscure/json-api#66]
Wouldn't it be nice if we could typehint what model we're throwing to the serializers? 

```php
public function getAttributes(User $user) {
    //
}
```

Would this be possible to implement and would it take long time to do?

**Comment by tobscure** [comment]
Not really possible because the serializers must adhere to an interface, so they can't stray from that with type hints.

Instead, you can do something like this:

```
public function getAttributes($user) {
    if (!($user instanceof User)) {
        throw new InvalidArgumentException;
    }
}
```

**Comment by vinkla** [comment]
Okay, to bad.

**Comment by vinkla** [comment]
@tobscure do you have any examples or tips for integrating the new version with Laravel?

**Comment by tobscure** [comment]
See [these methods](https://github.com/flarum/core/blob/master/src/Api/Serializer/AbstractSerializer.php#L134-L199) for an example implementation

**Comment by vinkla** [comment]
Thanks! How would go about binding the document to Laravel request?

**Comment by tobscure** [comment]
The Document object implements the JsonSerializable interface so you should be able to pass it right into the `response` helper, e.g.:

```php
return response($content)
            ->header('Content-Type', 'application/vnd.api+json');
```

**Comment by vinkla** [comment]
Awesome. Thanks for helping out!
