### ISSUE TITLE
Included resources

### ISSUE THREAD

**Issue by martin-hoger** [tobscure/json-api#68]
Hi Toby, thank you for the nice tool.

When I add a relationship, "id" and "type" is present. This works fine. I just didn't figure out how to add the resources as "included" data (see the example at http://jsonapi.org/, people, comments are included).

Is there a way to do that?

**Comment by tobscure** [comment]
You worked it out?

**Comment by martin-hoger** [comment]
It was my mistake in the serializer that I used for the relationship.
