### ISSUE TITLE
SerializerAbstract attempts to access the Id property directly

### ISSUE THREAD

**Issue by skqr** [tobscure/json-api#7]
I think it would make a lot more sense to use a getter - that way we can maintain encapsulation.

**Comment by bnchdrff** [comment]
Having a setter would help with #8.

**Comment by bnchdrff** [comment]
my change in 
https://github.com/bnchdrff/json-api/commit/2f418c15e8001728321e048637d99a12d5cf6bb1 preserves original behavior (expecting `$data->id` to be set) but allows your serializer implementation to define its own `getId`, like 

```php
protected function getId($ec_term) {
  return entity_extract_ids('taxonomy_term', $ec_term)[0];
}
```

**Comment by bnchdrff** [comment]
thanks!

**Comment by tobscure** [comment]
No problem! For the record, I decided to go with the method name `id` instead of `getId` just to be consistent with the `attributes` method
