### ISSUE TITLE
Parameters' getLimit returns string

### ISSUE THREAD

**Issue by byCedric** [tobscure/json-api#71]
I was implementing the package at _yet_ another project, until I noticed that the [`Parameters` own `getLimit`](https://github.com/tobscure/json-api/blob/v0.2.1/src/Parameters.php#L101) returns a string. Yes, it does state in the [docblock](https://github.com/tobscure/json-api/blob/v0.2.1/src/Parameters.php#L99) that it _should_ return a string but I find this quite confusing. Mostly because within the `LinksTrait` `addPaginationLinks` the limit is used as an integer...

My main point is should the [`getLimit` method within `Parameters`](https://github.com/tobscure/json-api/blob/v0.2.1/src/Parameters.php#L101) not return integer, and **0** by default instead of **''**.

**Comment by tobscure** [comment]
Agreed, PR welcome.

**Comment by byCedric** [comment]
Sure, just one more question. If no `$max` is provided, and no query was set, it should return **0** right? But what if a `$max` is, but no query was set. Should it still return **0**, or the provided `$max`? The last one is more useful I think since you do not depend on user input, by default.
Will write a PR in the morning!

**Comment by tobscure** [comment]
No, it should return **0** in both cases. This is because an app may want to have different *default* limit to its *max* limit, so it needs to be able to tell when no query was set. e.g. https://github.com/flarum/core/blob/master/src/Api/Controller/AbstractSerializeController.php#L179

**Comment by byCedric** [comment]
I would go for `null`, since it is the more literal description of what is happening with the limit value. It also is a falsy value, so it has no effect when using it in expressions like `if ($param->getLimit()) ...`. Even if you still want an int value, you can cast it to **0**. Will write a PR now, thanks for your input!
