### ISSUE TITLE
Weird Collection::fields() method behavior 

### ISSUE THREAD

**Issue by guillemcanal** [tobscure/json-api#76]
Hi,

Let me illustrate a behavior, which I consider to be counter-intuitive when using the `Collection::fields()` method.

Given a `$users` variables, which is an array of `User` objects.

``` php
$collection = (new Collection($users, new UsersSerializer()))
    ->with(['picture'])
    ->fields([
        'users' => ['name'],
        'picture' => ['large'],
    ]);

$document = new Document($collection);

print json_encode($document->toArray(), JSON_PRETTY_PRINT);
```

it will return:

``` json
{
    "data": [
        {
            "type": "users",
            "id": "2e758e05-ec02-49c2-a27b-4948aefb9115",
            "attributes": {
                "name": "Pierre"
            }
        },
        {
            "type": "users",
            "id": "2e758e05-ec02-49c2-a27b-4948aefb9115",
            "attributes": {
                "name": "Paul"
            }
        }
    ]
}
```

In this case, the resulting JSON object is missing **pictures** relationships even if I explicitly specified the need of this relation in the  `Collection::with()` method.

I discovered that if I provide a `picture` field for the `users` index, it will display the picture relationship in the resulting JSON object.

``` php
$collection = (new Collection($users, new UsersSerializer()))
    ->with(['picture'])
    ->fields([
        'users' => ['name', 'picture'],
        'picture' => ['large'],
    ]);

$document = new Document($collection);

print json_encode($document->toArray(), JSON_PRETTY_PRINT);
```

Is it a desired behavior ? I which case it is useful since the `Collection::with()` already express the need to attach any given relationships to a resource?

The piece of code responsible for this behavior can be found here: https://github.com/tobscure/json-api/blob/master/src/Resource.php#L212

Anyway, thanks a lot for this well crafted library ;)

**Comment by tobscure** [comment]
Yes you're right I think. It's not super clear in the spec, but I think [this part](http://jsonapi.org/format/#fetching-sparse-fieldsets) implies that the relationship should be included if specified, even if the linkage field is excluded.

**Comment by guillemcanal** [comment]
@tobscure Indeed, the spec is even more confusing. We may have better luck asking the json-api maintainer.

**Comment by tobscure** [comment]
It seems that the current behaviour (excluding the relationship field if it is not specified in the sparse fieldset) is [correct](http://discuss.jsonapi.org/t/clarification-on-the-sparse-fieldset-response/221/11).

**Comment by tobscure** [comment]
Also just noticed that the behaviour is explicitly defined in [this example](http://jsonapi.org/examples/#sparse-fieldsets).
