### ISSUE TITLE
Allow relationships without "data" object

### ISSUE THREAD

**Issue by josephmcdermott** [tobscure/json-api#84]
From what I can see, the inclusion of relationships in this library will always result in the addition of:
- a data object within the relationships object
- the included object being populated

I am trying to implement a billboard response like this:
```
{
    "data": {
        "type": "home",
        "id": "1",
        "links": {
            "self": "http://api.example.com"
        },
        "relationships": {
            "products": {
                "links": {
                    "related": "http://api.example.com/products"
                }
            }
        }
    }
}
```

Notice the above does not contain relationships:products:data, which is intentional. It also does not contain the included section at the bottom.

From what I can gather, your implementation of relationships assumes there will always be some data, is that correct? I am hoping I have missed something and there is an easy way to achieve the above.

**Comment by vinkla** [comment]
What does the [specification](http://jsonapi.org/format/) say about this?

**Comment by neomerx** [comment]
The spec [says](http://jsonapi.org/format/#document-resource-object-relationships)
> A "relationship object" MUST contain at least one of the following: links, data, meta

So just `links` is fine. As for `links` the spec says

> links: a links object containing at least one of the following: self, related

So just [related](http://jsonapi.org/format/#document-resource-object-related-resource-links) is fine as well.

**Comment by neomerx** [comment]
@josephmcdermott the `related` value should rather be `http://api.example.com/home/1/products` and type name `home` should probably be changed as well.

**Comment by josephmcdermott** [comment]
Yes, as you stated the example I've posted does conform to JSON API specification. Your point about /home/1/products is an interesting one, since I am not actually trying to represent a relationship to the homepage, I am simply trying to represent "here is where to go next to find all of the main starting points of this API", namely products in this example. (I started this discussion on JSON API forum: http://discuss.jsonapi.org/t/how-to-format-a-rest-api-billboard-homepage-response/384

@neomerx what is the 'easy way' to achieve this? Is the answer to not use this library? :)

**Comment by josephmcdermott** [comment]
As per the above comment, I have submitted a PR with a simple fix to allow this.

**Comment by samgreenwood** [comment]
This looks like exactly what I'm looking for, what are you doing to add the relationship to the Resource as the code relies on it being included at the moment.

**Comment by tobscure** [comment]
Closed with the merge of #85

**Comment by tobscure** [comment]
Can anyone tell me regarding semver if this is a breaking change or not? Does it warrant a bump to 0.3?

**Comment by franzliedke** [comment]
Technically it definitely breaks BC. Given how many changes have been made, 0.3 makes sense, I'd say.

Making some of these classes `final` sounds like a logical step, too.

**Comment by tobscure** [comment]
Alright, I will prepare a 0.3 release soon :)
