### ISSUE TITLE
getPage() methods for Parameters

### ISSUE THREAD

**Issue by gossi** [tobscure/json-api#93]
I was wondering if there could be more page related methods in `Parameters` or at least making `getPage()` a public method. Here's something I'm looking for:

```
$page = $params->getPage('number');
$size = $params->getPage('size', $defaultSize);
```

would sound wrong to use different methods just for that, when everything else are methods on `Parameters` as well.

**Comment by tobscure** [comment]
You can use the existing `getOffset` and `getLimit` methods to achieve what you want:

```php
// input: ?page[number]=4&page[size]=10

$size = $params->getLimit() ?: $defaultSize; // 10
$offset = $params->getOffset($size); // 40
$page = $offset / $size; // 4
```

**Comment by gossi** [comment]
Nah. There are two concepts adressing pagination: offset/limit or page(number)/size. I'd go with the methods if they match my strategy but they don't. I subclassed your Parameters and made getPage public:

```php
use Tobscure\JsonApi\Parameters as BaseParameters;
class Parameters extends BaseParameters {
	
	public function getPage($key, $default = null) {
		$page = $this->getInput('page', []);
		
		return isset($page[$key]) ? $page[$key] : $default;
	}
}
```

**Comment by tobscure** [comment]
How does my code snippet not work for you though? `limit` is synonymous with `size`, and the correct page `number` can be derived from the calculated `offset` and `size`.

**Comment by gossi** [comment]
It's more of a mental thing. I'm looking for page number and size, instead I only have methods for limit and offset and need to do a calculation aftewards, while I now my parameters are `page[number]` and `page[size]` - that feels like doing it wrong. I want to use number for number and size for size and not limit for size or offset + formula for number.
I know these values are there and want to access them straight ahead, instead it says: "No please use this 'complex' formula instead".
Sorry, if this sounds harsh or something (it isn't). It is just for you to understand my position - hope you get it.
